spring.application.name=app


spring.datasource.url=jdbc:postgresql://localhost:5432/mapreduce_db
spring.datasource.username=zhappar_a
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

secret.key=8Cr6eIxMt8xVSJ7Ffi5uIEidC0cWUaiDlARbKKSNp4S

bucket4j.enabled=false

app.storage.location = "./storage"

total.thread.count = 8
count.words.average.time = 30.00
count.words.chunk.size = 134217728
